/*
DROP TABLE STORE_BOOKINGS;
DROP TABLE STORE_PRODUCTS;
DROP TABLE STORE_DEPARTMENTS;
DROP TABLE STORE_CLIENTS;*/
/*
alter table STORE_DISTRIBUTORS modify(title varchar2(80));
commit;
alter table STORE_PRODUCTS modify(name_pr varchar2(80));
commit;
alter table STORE_PRODUCTS modify(date_pr DATE);
commit;
alter table STORE_BOOKINGS modify(date_b DATE);
commit;*/

/*
CREATE TABLE STORE_CLIENTS( 
id_client NUMBER(8) NOT NULL PRIMARY KEY,
fio VARCHAR2(80) NOT NULL,
tel_client NUMBER(8)
);


CREATE TABLE STORE_DISTRIBUTORS( 
id_distrib NUMBER(8) NOT NULL PRIMARY KEY,
title varchar2(80), 
tel_dep NUMBER(8)
);

CREATE TABLE STORE_PRODUCTS( 
id_product NUMBER(8) NOT NULL PRIMARY KEY,
id_distrib_fk NUMBER(8) NOT NULL REFERENCES STORE_DISTRIBUTORS(ID_DISTRIB), 
name_pr varchar2(80) NOT NULL,
cost_pr NUMBER(8) NOT NULL,
date_pr DATE NOT NULL,
storage_pr NUMBER(8) NOT NULL,
existence NUMBER(8) DEFAULT 0
);

CREATE TABLE STORE_BOOKINGS( 
id_booking NUMBER(8) NOT NULL PRIMARY KEY,
id_product_fk NUMBER(8) NOT NULL REFERENCES STORE_PRODUCTS(ID_PRODUCT), 
id_client_fk NUMBER(8) NOT NULL REFERENCES STORE_CLIENTS(ID_CLIENT),
sum_b NUMBER(8) NOT NULL,
quantity_b NUMBER(8) NOT NULL,
date_b NUMBER(8) NOT NULL
);
*/
